
    




CREATE OR REPLACE PROCEDURE GET_CUST_COMP_NAME(C_ID IN NUMBER, CURSOR_ OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN CURSOR_ FOR
    SELECT FIRSTNAME, LASTNAME, COMPANY
    FROM CUSTOMER
    WHERE CUSTOMERID = C_ID;
END;

EXECUTE GET_CUST_COMP_NAME(60);
DECLARE
S SYS_REFCURSOR;

SOME_ID BEAR.BEAR_ID%TYPE; --DECLARES SOME ID AS WHATEVER TYPE BEAR.BEAR_ID IS
SOME_NAME BEAR.BEAR_NAME%TYPE;
BEGIN 
    S := PRINT_ALL_BEARS;
    LOOP
        FETCH S INTO SOME_ID, SOME_NAME;
        EXIT WHEN S%NOTFOUND; --BREAK OUT OF LOOP WHEN NO ROWS ARE AVAILABLE
        DBMS_OUTPUT.PUT_LINE(' ID: '||SOME_ID||', NAME: '|| SOME_NAME);
    END LOOP;
    CLOSE S;
END; 